const videoInput=document.querySelector("#videoInput"),videoInfo=document.querySelector("#videoInfo"),statusEl=document.querySelector("#status"),testBtn=document.querySelector("#testBtn"),preview=document.querySelector("#preview"),before=document.querySelector("#before"),after=document.querySelector("#after"),resultText=document.querySelector("#resultText"),progressWrap=document.querySelector("#progressWrap"),progressBar=document.querySelector("#progressBar"),progressText=document.querySelector("#progressText");
let file=null,session=null,gpuReady=false;

// FIXED: verified Real-ESRGAN ONNX model location.
const MODEL_URL="https://huggingface.co/Heliosoph/realesrgan-onnx/resolve/main/realesr-general-x4v3.onnx";

const setProgress=v=>{v=Math.max(0,Math.min(100,Math.round(v)));progressBar.style.width=v+"%";progressText.textContent=v+"%"};
const status=(s,e=false)=>statusEl.textContent=(e?"❌ ":"")+s;
function showError(e){console.error(e);const m=e?.message||String(e);status(m.slice(0,500),true);resultText.textContent="Technical error: "+m.slice(0,700);preview.classList.remove("hidden");testBtn.disabled=false}
async function initGPU(){if(!("gpu" in navigator)){status("WebGPU is not available in this browser.",true);return false}try{const a=await navigator.gpu.requestAdapter({powerPreference:"high-performance"});if(!a){status("No compatible GPU adapter found.",true);return false}gpuReady=true;status("WebGPU available. AI can run locally in this browser.");return true}catch(e){showError(e);return false}}
async function loadModel(){if(!gpuReady)throw Error("WebGPU is not ready.");status("Loading AI model…");setProgress(5);session=await ort.InferenceSession.create(MODEL_URL,{executionProviders:["webgpu","wasm"],graphOptimizationLevel:"all"});console.log("inputs",session.inputNames,"outputs",session.outputNames);if(!session.inputNames.length||!session.outputNames.length)throw Error("AI model loaded but no input/output nodes were found.");setProgress(20);status("AI model loaded. Ready for frame test.")}
function meta(f){return new Promise((res,rej)=>{const v=document.createElement("video");v.preload="metadata";v.onloadedmetadata=()=>{res({duration:v.duration,width:v.videoWidth,height:v.videoHeight});URL.revokeObjectURL(v.src)};v.onerror=()=>rej(Error("Could not read video metadata."));v.src=URL.createObjectURL(f)})}
function seek(v,t){return new Promise((res,rej)=>{let timer;const done=()=>{clearTimeout(timer);res()};v.addEventListener("seeked",done,{once:true});v.currentTime=t;timer=setTimeout(()=>rej(Error("Video seek timed out.")),15000)})}
function tensor(canvas){const w=canvas.width,h=canvas.height,d=canvas.getContext("2d",{willReadFrequently:true}).getImageData(0,0,w,h).data,p=w*h,a=new Float32Array(3*p);for(let x=0,i=0;x<p;x++,i+=4){a[x]=d[i]/255;a[p+x]=d[i+1]/255;a[2*p+x]=d[i+2]/255}return new ort.Tensor("float32",a,[1,3,h,w])}
function draw(t,c){if(!t?.dims||t.dims.length!==4)throw Error("AI returned an invalid output tensor.");const [n,ch,h,w]=t.dims;if(n!==1||ch<3)throw Error("Unexpected AI output shape: "+t.dims.join(" × "));c.width=w;c.height=h;const d=t.data,o=new Uint8ClampedArray(w*h*4),p=w*h;for(let x=0;x<p;x++){o[x*4]=Math.max(0,Math.min(255,Math.round(d[x]*255)));o[x*4+1]=Math.max(0,Math.min(255,Math.round(d[p+x]*255)));o[x*4+2]=Math.max(0,Math.min(255,Math.round(d[2*p+x]*255)));o[x*4+3]=255}c.getContext("2d").putImageData(new ImageData(o,w,h),0,0)}
async function test(){if(!file)throw Error("Please select a video first.");if(!session)throw Error("AI model is not ready yet.");testBtn.disabled=true;progressWrap.classList.remove("hidden");preview.classList.remove("hidden");setProgress(25);status("Preparing one frame for AI…");const v=document.createElement("video");v.muted=true;v.playsInline=true;v.preload="auto";v.src=URL.createObjectURL(file);try{await new Promise((r,j)=>{v.onloadedmetadata=r;v.onerror=()=>j(Error("Video decode failed."))});await seek(v,Math.min(.5,Math.max(0,v.duration/2)));const max=320,s=Math.min(1,max/Math.max(v.videoWidth,v.videoHeight)),w=Math.max(16,Math.round(v.videoWidth*s)),h=Math.max(16,Math.round(v.videoHeight*s));before.width=w;before.height=h;before.getContext("2d").drawImage(v,0,0,w,h);setProgress(40);status("Running AI on "+w+"×"+h+" frame…");const r=await session.run({[session.inputNames[0]]:tensor(before)}),o=r[session.outputNames[0]];if(!o)throw Error("AI completed but output was not returned.");setProgress(90);draw(o,after);setProgress(100);resultText.textContent=`SUCCESS: ${w}×${h} → ${after.width}×${after.height}. Frame processed locally on your phone.`;status("AI frame test complete. No video was uploaded.")}finally{URL.revokeObjectURL(v.src);testBtn.disabled=false}}
videoInput.addEventListener("change",async()=>{file=videoInput.files?.[0]||null;testBtn.disabled=true;preview.classList.add("hidden");setProgress(0);if(!file)return;try{const m=await meta(file),limit=10;videoInfo.classList.remove("hidden");videoInfo.textContent=`${file.name} • ${m.width}×${m.height} • ${m.duration.toFixed(1)} sec`;if(m.duration>limit){status(`Prototype limit is ${limit} seconds. Final V1 target will be 30 seconds.`,true);return}if(await initGPU()){await loadModel();testBtn.disabled=false}}catch(e){showError(e)}});
testBtn.addEventListener("click",()=>test().catch(showError));initGPU().catch(showError);